### ISSUE TITLE
EC2 Instance Profile support for AWS Credentials

### ISSUE THREAD

**Issue by akranga** [jenkinsci/aws-credentials-plugin#18]
We actually need this for `amazon-ecr-plugin` but seems this plugin is actually is the right place. Otherwise it limits usage of ECR in pipelines when EC2 Instance Profile
```
withRegistry('xyz', 'ecr:credentials-id') {
...
}
```

Add Instance Profile support to `AWSCredentialsImpl`. Change is as simple as that:
```
method getCredentials()
...
def credProv = InstanceProfileCredentialsProvider.getInstance()
```

**Comment by akranga** [comment]
If this approved I can send a PR

**Comment by lewisgj** [comment]
You might have already thought about this but one thing to consider is that in a master-slave set up slaves will/can have a different instance profile to the master - I have a use case where slaves have different permissions, so getting the instance profile on the master won't work for me. (Instead the answer would be to make a remote call to the slave requesting the credentials, if that's possible)
