### ISSUE TITLE
AWS_SESSION_TOKEN environment variable not being set

### ISSUE THREAD

**Issue by nathandines** [jenkinsci/aws-credentials-plugin#19]
When using an access key to assume an IAM role, the AWS_SESSION_TOKEN environment variable is not being set.

I was looking through the code, and feel like the issue might be in [this file](https://github.com/jenkinsci/aws-credentials-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java), but I'm not a Java dev, and would appreciate if someone more experienced in that area could please take a look at this.

I'm using a Jenkins Pipeline to provide the credentials to my build. See this pipeline example snippet:
```
withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
  sh 'env'
}
```

env Output:
```
+ env
JENKINS_HOME=/var/jenkins_home
no_proxy=127.0.0.1
RUN_CHANGES_DISPLAY_URL=http://localhost:8080/job/aws-infra/18/display/redirect?page=changes
HOSTNAME=95f289c8ae68
NODE_LABELS=master
HUDSON_URL=http://localhost:8080/
SHLVL=0
HOME=/var/jenkins_home
BUILD_URL=http://localhost:8080/job/aws-infra/18/
HUDSON_COOKIE=64220461-ba1b-4309-b4be-1d1a09324522
JENKINS_SERVER_COOKIE=durable-09bfba379178a45fd0395d8babc98540
WORKSPACE=/var/jenkins_home/workspace/aws-infra
JAVA_VERSION=8u121
NODE_NAME=master
CA_CERTIFICATES_JAVA_VERSION=20161107~bpo8+1
EXECUTOR_NUMBER=0
TINI_SHA=fa23d1e20732501c3bb8eeeca423c89ac80ed452
BUILD_DISPLAY_NAME=#18
HUDSON_HOME=/var/jenkins_home
JOB_BASE_NAME=aws-infra
JAVA_DEBIAN_VERSION=8u121-b13-1~bpo8+1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BUILD_ID=18
BUILD_TAG=jenkins-aws-infra-18
LANG=C.UTF-8
JENKINS_URL=http://localhost:8080/
JOB_URL=http://localhost:8080/job/aws-infra/
BUILD_NUMBER=18
RUN_DISPLAY_URL=http://localhost:8080/job/aws-infra/18/display/redirect
AWS_ACCESS_KEY_ID=****
JENKINS_SLAVE_AGENT_PORT=50000
AWS_SECRET_ACCESS_KEY=****
HUDSON_SERVER_COOKIE=23073d19f5a26cc1
JOB_DISPLAY_URL=http://localhost:8080/job/aws-infra/display/redirect
JOB_NAME=aws-infra
COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
PWD=/var/jenkins_home/workspace/aws-infra
TINI_VERSION=0.9.0
```

**Comment by AlexejK** [comment]
Just hit this issue too when tried to setup cross-account access for our jobs. Had to fix it with #20 and also added a nice-to-have thing for credentials to allow using instance profile credentials.

I can provide a pre-compiled plugin for you if needed @nathandines

**Comment by AlexejK** [comment]
HPI file for the PR is available here if needed: https://github.com/AlexejK/aws-credentials-plugin/releases/tag/aws-credentials-1.20-pr20 and it can be installed via manual upload in Jenkins Manage Plugins > Advanced

**Comment by nathandines** [comment]
Thanks for acting so quickly on this. I only just got around to testing it.

Unfortunately, it seems that the patch didn't work for me.

`AWS_SESSION_TOKEN` is still not being presented as an environment variable, and now the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` is no longer being obfuscated in the build logs.

**Comment by AlexejK** [comment]
That's interesting because it is obfuscated for me and doing shell test with output of env sets it all properly. 

this patch detects if the credentials are session based or not.

**Comment by AlexejK** [comment]
I've rebased the plugin on-top of newly released 1.20 and updated my draft release.
https://github.com/AlexejK/aws-credentials-plugin/releases/tag/aws-credentials-1.21-pr20 and it's working as part of non-pipeline job where i first assign AWS Credentials to env variables and then perform print-out of `env`. 

I just noticed you are using pipleines so I will check pipelines on my setup in a bit

**Comment by AlexejK** [comment]
@nathandines, The following basic pipeline seems to print-out proper information and credentials are validated by checking output of `sh 'aws s3 ls'`

```
node {
    stage("Test") {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-with-role']]) {
          sh 'env'
          sh 'aws s3 ls'
        }
    }
}
```

Output of `sh 'env'` is properly redacted for `AWS_ACCESS_KEY`, `AWS_SESSION_TOKEN`, `AWS_SECRET_KEY` variables.

Can you provide a sample that seems to be breaking for you? possible information about how your pipeline & credentials are configured?

**Comment by nathandines** [comment]
The scenario I'm talking about is where you assume an IAM role by first using IAM User access keys to perform the "assume".

Are you assuming a role using an IAM role associated with the master, or are you assuming a role using access keys defined in the credentials configuration on the master?

When I tested it using an IAM role on an EC2 instance it was working well. The issue seems to be when using access keys to assume the role.

**Comment by AlexejK** [comment]
Thanks for update - I've actually tested both combinations IIRC. Will re-test this case again. 

Do you mind trying a slightly updated version? It's mainly rebased with 1.20 release fixes.
https://github.com/AlexejK/aws-credentials-plugin/releases/tag/aws-credentials-1.21-pr20
