### ISSUE TITLE
Error assuming IAM role in Jenkins (es_ES)

### ISSUE THREAD

**Issue by diegombeltran** [jenkinsci/aws-credentials-plugin#67]
`Exception searching clusters for credentials=Test, regionName=eu-west-1:com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: 1 validation error detected: Value 'Jenkins ' at 'roleSessionName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]* (Service: AWSSecurityTokenService; Status Code: 400; Error Code: ValidationError; Request ID: 20e28d0c-b8ff-11e9-8b33-4d7def127bc0)`

Looks like roleSessionName is wrong, as it includes a whitespace which breaks the assumeRole action. It doesn't happen in other languages. Forcing Jenkins to use en_GB locales (Using locale plugin for example) fixes it.

[This is the Jenkins file which contains the bad property](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/Messages_es.properties)

**Comment by oleg-nenashev** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-58842 FTR
