### ISSUE TITLE
AWS SDK update needed to use Kubernetes ServiceAccount credentials

### ISSUE THREAD

**Issue by jasonstitt** [jenkinsci/aws-credentials-plugin#78]
`aws-sdk-java` needs to be at least 1.11.704 in order for AWS credentials from a Kubernetes ServiceAccount to be part of the default credentials chain. (See: https://github.com/aws/aws-sdk-java/issues/2136#issuecomment-574820525 ) This would allow Jenkins to be run on e.g. EKS using native AWS credential setup and then assume other roles from there. From the comments, looks like adding `aws-java-sdk-sts` is also needed for this.

**Comment by olivernaaris** [comment]
Would be awesome if this gets included.
